#!/usr/bin/sh
miranda neg_1_mirna.fas neg_1_target.fas -strict > neg_1_miranda_results.txt
miranda neg_2_mirna.fas neg_2_target.fas -strict > neg_2_miranda_results.txt
miranda neg_3_mirna.fas neg_3_target.fas -strict > neg_3_miranda_results.txt
miranda neg_4_mirna.fas neg_4_target.fas -strict > neg_4_miranda_results.txt
miranda neg_5_mirna.fas neg_5_target.fas -strict > neg_5_miranda_results.txt
miranda neg_6_mirna.fas neg_6_target.fas -strict > neg_6_miranda_results.txt
miranda neg_7_mirna.fas neg_7_target.fas -strict > neg_7_miranda_results.txt
miranda neg_8_mirna.fas neg_8_target.fas -strict > neg_8_miranda_results.txt
miranda neg_9_mirna.fas neg_9_target.fas -strict > neg_9_miranda_results.txt
miranda neg_10_mirna.fas neg_10_target.fas -strict > neg_10_miranda_results.txt
miranda neg_11_mirna.fas neg_11_target.fas -strict > neg_11_miranda_results.txt
miranda neg_12_mirna.fas neg_12_target.fas -strict > neg_12_miranda_results.txt
miranda neg_13_mirna.fas neg_13_target.fas -strict > neg_13_miranda_results.txt
miranda neg_14_mirna.fas neg_14_target.fas -strict > neg_14_miranda_results.txt
miranda neg_15_mirna.fas neg_15_target.fas -strict > neg_15_miranda_results.txt
miranda neg_16_mirna.fas neg_16_target.fas -strict > neg_16_miranda_results.txt
miranda neg_17_mirna.fas neg_17_target.fas -strict > neg_17_miranda_results.txt
miranda neg_18_mirna.fas neg_18_target.fas -strict > neg_18_miranda_results.txt
miranda neg_19_mirna.fas neg_19_target.fas -strict > neg_19_miranda_results.txt
miranda neg_20_mirna.fas neg_20_target.fas -strict > neg_20_miranda_results.txt
miranda neg_21_mirna.fas neg_21_target.fas -strict > neg_21_miranda_results.txt
miranda neg_22_mirna.fas neg_22_target.fas -strict > neg_22_miranda_results.txt
miranda neg_23_mirna.fas neg_23_target.fas -strict > neg_23_miranda_results.txt
miranda neg_24_mirna.fas neg_24_target.fas -strict > neg_24_miranda_results.txt
miranda neg_25_mirna.fas neg_25_target.fas -strict > neg_25_miranda_results.txt
miranda neg_26_mirna.fas neg_26_target.fas -strict > neg_26_miranda_results.txt
miranda neg_27_mirna.fas neg_27_target.fas -strict > neg_27_miranda_results.txt
miranda neg_28_mirna.fas neg_28_target.fas -strict > neg_28_miranda_results.txt
miranda neg_29_mirna.fas neg_29_target.fas -strict > neg_29_miranda_results.txt
miranda neg_30_mirna.fas neg_30_target.fas -strict > neg_30_miranda_results.txt
miranda neg_31_mirna.fas neg_31_target.fas -strict > neg_31_miranda_results.txt
miranda neg_32_mirna.fas neg_32_target.fas -strict > neg_32_miranda_results.txt
miranda neg_33_mirna.fas neg_33_target.fas -strict > neg_33_miranda_results.txt
miranda neg_34_mirna.fas neg_34_target.fas -strict > neg_34_miranda_results.txt
miranda neg_35_mirna.fas neg_35_target.fas -strict > neg_35_miranda_results.txt
miranda neg_36_mirna.fas neg_36_target.fas -strict > neg_36_miranda_results.txt
miranda neg_37_mirna.fas neg_37_target.fas -strict > neg_37_miranda_results.txt
miranda neg_38_mirna.fas neg_38_target.fas -strict > neg_38_miranda_results.txt
miranda neg_39_mirna.fas neg_39_target.fas -strict > neg_39_miranda_results.txt
miranda neg_40_mirna.fas neg_40_target.fas -strict > neg_40_miranda_results.txt
miranda neg_41_mirna.fas neg_41_target.fas -strict > neg_41_miranda_results.txt
miranda neg_42_mirna.fas neg_42_target.fas -strict > neg_42_miranda_results.txt
miranda neg_43_mirna.fas neg_43_target.fas -strict > neg_43_miranda_results.txt
miranda neg_44_mirna.fas neg_44_target.fas -strict > neg_44_miranda_results.txt
miranda neg_45_mirna.fas neg_45_target.fas -strict > neg_45_miranda_results.txt
miranda neg_46_mirna.fas neg_46_target.fas -strict > neg_46_miranda_results.txt
miranda neg_47_mirna.fas neg_47_target.fas -strict > neg_47_miranda_results.txt
miranda neg_48_mirna.fas neg_48_target.fas -strict > neg_48_miranda_results.txt
miranda neg_49_mirna.fas neg_49_target.fas -strict > neg_49_miranda_results.txt
miranda neg_50_mirna.fas neg_50_target.fas -strict > neg_50_miranda_results.txt
miranda neg_51_mirna.fas neg_51_target.fas -strict > neg_51_miranda_results.txt
miranda neg_52_mirna.fas neg_52_target.fas -strict > neg_52_miranda_results.txt
miranda neg_53_mirna.fas neg_53_target.fas -strict > neg_53_miranda_results.txt
miranda neg_54_mirna.fas neg_54_target.fas -strict > neg_54_miranda_results.txt
miranda neg_55_mirna.fas neg_55_target.fas -strict > neg_55_miranda_results.txt
miranda neg_56_mirna.fas neg_56_target.fas -strict > neg_56_miranda_results.txt
miranda neg_57_mirna.fas neg_57_target.fas -strict > neg_57_miranda_results.txt
miranda neg_58_mirna.fas neg_58_target.fas -strict > neg_58_miranda_results.txt
miranda neg_59_mirna.fas neg_59_target.fas -strict > neg_59_miranda_results.txt
miranda neg_60_mirna.fas neg_60_target.fas -strict > neg_60_miranda_results.txt
miranda neg_61_mirna.fas neg_61_target.fas -strict > neg_61_miranda_results.txt
miranda neg_62_mirna.fas neg_62_target.fas -strict > neg_62_miranda_results.txt
miranda neg_63_mirna.fas neg_63_target.fas -strict > neg_63_miranda_results.txt
miranda neg_64_mirna.fas neg_64_target.fas -strict > neg_64_miranda_results.txt
miranda neg_65_mirna.fas neg_65_target.fas -strict > neg_65_miranda_results.txt
miranda neg_66_mirna.fas neg_66_target.fas -strict > neg_66_miranda_results.txt
miranda neg_67_mirna.fas neg_67_target.fas -strict > neg_67_miranda_results.txt
miranda neg_68_mirna.fas neg_68_target.fas -strict > neg_68_miranda_results.txt
miranda neg_69_mirna.fas neg_69_target.fas -strict > neg_69_miranda_results.txt
miranda neg_70_mirna.fas neg_70_target.fas -strict > neg_70_miranda_results.txt
miranda neg_71_mirna.fas neg_71_target.fas -strict > neg_71_miranda_results.txt
miranda neg_72_mirna.fas neg_72_target.fas -strict > neg_72_miranda_results.txt
miranda neg_73_mirna.fas neg_73_target.fas -strict > neg_73_miranda_results.txt
miranda neg_74_mirna.fas neg_74_target.fas -strict > neg_74_miranda_results.txt
miranda neg_75_mirna.fas neg_75_target.fas -strict > neg_75_miranda_results.txt
miranda neg_76_mirna.fas neg_76_target.fas -strict > neg_76_miranda_results.txt
miranda neg_77_mirna.fas neg_77_target.fas -strict > neg_77_miranda_results.txt
miranda neg_78_mirna.fas neg_78_target.fas -strict > neg_78_miranda_results.txt
miranda neg_79_mirna.fas neg_79_target.fas -strict > neg_79_miranda_results.txt
miranda neg_80_mirna.fas neg_80_target.fas -strict > neg_80_miranda_results.txt
miranda neg_81_mirna.fas neg_81_target.fas -strict > neg_81_miranda_results.txt
miranda neg_82_mirna.fas neg_82_target.fas -strict > neg_82_miranda_results.txt
miranda neg_83_mirna.fas neg_83_target.fas -strict > neg_83_miranda_results.txt
miranda neg_84_mirna.fas neg_84_target.fas -strict > neg_84_miranda_results.txt
miranda neg_85_mirna.fas neg_85_target.fas -strict > neg_85_miranda_results.txt
miranda neg_86_mirna.fas neg_86_target.fas -strict > neg_86_miranda_results.txt
miranda neg_87_mirna.fas neg_87_target.fas -strict > neg_87_miranda_results.txt
miranda neg_88_mirna.fas neg_88_target.fas -strict > neg_88_miranda_results.txt
miranda neg_89_mirna.fas neg_89_target.fas -strict > neg_89_miranda_results.txt
miranda neg_90_mirna.fas neg_90_target.fas -strict > neg_90_miranda_results.txt
miranda neg_91_mirna.fas neg_91_target.fas -strict > neg_91_miranda_results.txt
miranda neg_92_mirna.fas neg_92_target.fas -strict > neg_92_miranda_results.txt
miranda neg_93_mirna.fas neg_93_target.fas -strict > neg_93_miranda_results.txt
miranda neg_94_mirna.fas neg_94_target.fas -strict > neg_94_miranda_results.txt
miranda neg_95_mirna.fas neg_95_target.fas -strict > neg_95_miranda_results.txt
miranda neg_96_mirna.fas neg_96_target.fas -strict > neg_96_miranda_results.txt
miranda neg_97_mirna.fas neg_97_target.fas -strict > neg_97_miranda_results.txt
miranda neg_98_mirna.fas neg_98_target.fas -strict > neg_98_miranda_results.txt
miranda neg_99_mirna.fas neg_99_target.fas -strict > neg_99_miranda_results.txt
miranda neg_100_mirna.fas neg_100_target.fas -strict > neg_100_miranda_results.txt
miranda neg_101_mirna.fas neg_101_target.fas -strict > neg_101_miranda_results.txt
miranda neg_102_mirna.fas neg_102_target.fas -strict > neg_102_miranda_results.txt
miranda neg_103_mirna.fas neg_103_target.fas -strict > neg_103_miranda_results.txt
miranda neg_104_mirna.fas neg_104_target.fas -strict > neg_104_miranda_results.txt
miranda neg_105_mirna.fas neg_105_target.fas -strict > neg_105_miranda_results.txt
miranda neg_106_mirna.fas neg_106_target.fas -strict > neg_106_miranda_results.txt
miranda neg_107_mirna.fas neg_107_target.fas -strict > neg_107_miranda_results.txt
miranda neg_108_mirna.fas neg_108_target.fas -strict > neg_108_miranda_results.txt
miranda neg_109_mirna.fas neg_109_target.fas -strict > neg_109_miranda_results.txt
miranda neg_110_mirna.fas neg_110_target.fas -strict > neg_110_miranda_results.txt
miranda neg_111_mirna.fas neg_111_target.fas -strict > neg_111_miranda_results.txt
miranda neg_112_mirna.fas neg_112_target.fas -strict > neg_112_miranda_results.txt
miranda neg_113_mirna.fas neg_113_target.fas -strict > neg_113_miranda_results.txt
miranda neg_114_mirna.fas neg_114_target.fas -strict > neg_114_miranda_results.txt
miranda neg_115_mirna.fas neg_115_target.fas -strict > neg_115_miranda_results.txt
miranda neg_116_mirna.fas neg_116_target.fas -strict > neg_116_miranda_results.txt
miranda neg_117_mirna.fas neg_117_target.fas -strict > neg_117_miranda_results.txt
miranda neg_118_mirna.fas neg_118_target.fas -strict > neg_118_miranda_results.txt
miranda neg_119_mirna.fas neg_119_target.fas -strict > neg_119_miranda_results.txt
miranda neg_120_mirna.fas neg_120_target.fas -strict > neg_120_miranda_results.txt
miranda neg_121_mirna.fas neg_121_target.fas -strict > neg_121_miranda_results.txt
miranda neg_122_mirna.fas neg_122_target.fas -strict > neg_122_miranda_results.txt
miranda neg_123_mirna.fas neg_123_target.fas -strict > neg_123_miranda_results.txt
miranda neg_124_mirna.fas neg_124_target.fas -strict > neg_124_miranda_results.txt
miranda neg_125_mirna.fas neg_125_target.fas -strict > neg_125_miranda_results.txt
miranda neg_126_mirna.fas neg_126_target.fas -strict > neg_126_miranda_results.txt
miranda neg_127_mirna.fas neg_127_target.fas -strict > neg_127_miranda_results.txt
miranda neg_128_mirna.fas neg_128_target.fas -strict > neg_128_miranda_results.txt
miranda neg_129_mirna.fas neg_129_target.fas -strict > neg_129_miranda_results.txt
miranda neg_130_mirna.fas neg_130_target.fas -strict > neg_130_miranda_results.txt
miranda neg_131_mirna.fas neg_131_target.fas -strict > neg_131_miranda_results.txt
miranda neg_132_mirna.fas neg_132_target.fas -strict > neg_132_miranda_results.txt
miranda neg_133_mirna.fas neg_133_target.fas -strict > neg_133_miranda_results.txt
miranda neg_134_mirna.fas neg_134_target.fas -strict > neg_134_miranda_results.txt
miranda neg_135_mirna.fas neg_135_target.fas -strict > neg_135_miranda_results.txt
miranda neg_136_mirna.fas neg_136_target.fas -strict > neg_136_miranda_results.txt
miranda neg_137_mirna.fas neg_137_target.fas -strict > neg_137_miranda_results.txt
miranda neg_138_mirna.fas neg_138_target.fas -strict > neg_138_miranda_results.txt
miranda neg_139_mirna.fas neg_139_target.fas -strict > neg_139_miranda_results.txt
miranda neg_140_mirna.fas neg_140_target.fas -strict > neg_140_miranda_results.txt
miranda neg_141_mirna.fas neg_141_target.fas -strict > neg_141_miranda_results.txt
miranda neg_142_mirna.fas neg_142_target.fas -strict > neg_142_miranda_results.txt
miranda neg_143_mirna.fas neg_143_target.fas -strict > neg_143_miranda_results.txt
miranda neg_144_mirna.fas neg_144_target.fas -strict > neg_144_miranda_results.txt
miranda neg_145_mirna.fas neg_145_target.fas -strict > neg_145_miranda_results.txt
miranda neg_146_mirna.fas neg_146_target.fas -strict > neg_146_miranda_results.txt
miranda neg_147_mirna.fas neg_147_target.fas -strict > neg_147_miranda_results.txt
miranda neg_148_mirna.fas neg_148_target.fas -strict > neg_148_miranda_results.txt
miranda neg_149_mirna.fas neg_149_target.fas -strict > neg_149_miranda_results.txt
miranda neg_150_mirna.fas neg_150_target.fas -strict > neg_150_miranda_results.txt
miranda neg_151_mirna.fas neg_151_target.fas -strict > neg_151_miranda_results.txt
miranda neg_152_mirna.fas neg_152_target.fas -strict > neg_152_miranda_results.txt
miranda neg_153_mirna.fas neg_153_target.fas -strict > neg_153_miranda_results.txt
miranda neg_154_mirna.fas neg_154_target.fas -strict > neg_154_miranda_results.txt
miranda neg_155_mirna.fas neg_155_target.fas -strict > neg_155_miranda_results.txt
miranda neg_156_mirna.fas neg_156_target.fas -strict > neg_156_miranda_results.txt
miranda neg_157_mirna.fas neg_157_target.fas -strict > neg_157_miranda_results.txt
miranda neg_158_mirna.fas neg_158_target.fas -strict > neg_158_miranda_results.txt
miranda neg_159_mirna.fas neg_159_target.fas -strict > neg_159_miranda_results.txt
miranda neg_160_mirna.fas neg_160_target.fas -strict > neg_160_miranda_results.txt
miranda neg_161_mirna.fas neg_161_target.fas -strict > neg_161_miranda_results.txt
miranda neg_162_mirna.fas neg_162_target.fas -strict > neg_162_miranda_results.txt
miranda neg_163_mirna.fas neg_163_target.fas -strict > neg_163_miranda_results.txt
miranda neg_164_mirna.fas neg_164_target.fas -strict > neg_164_miranda_results.txt
miranda neg_165_mirna.fas neg_165_target.fas -strict > neg_165_miranda_results.txt
miranda neg_166_mirna.fas neg_166_target.fas -strict > neg_166_miranda_results.txt
miranda neg_167_mirna.fas neg_167_target.fas -strict > neg_167_miranda_results.txt
miranda neg_168_mirna.fas neg_168_target.fas -strict > neg_168_miranda_results.txt
miranda neg_169_mirna.fas neg_169_target.fas -strict > neg_169_miranda_results.txt
miranda neg_170_mirna.fas neg_170_target.fas -strict > neg_170_miranda_results.txt
miranda neg_171_mirna.fas neg_171_target.fas -strict > neg_171_miranda_results.txt
miranda neg_172_mirna.fas neg_172_target.fas -strict > neg_172_miranda_results.txt
miranda neg_173_mirna.fas neg_173_target.fas -strict > neg_173_miranda_results.txt
miranda neg_174_mirna.fas neg_174_target.fas -strict > neg_174_miranda_results.txt
miranda neg_175_mirna.fas neg_175_target.fas -strict > neg_175_miranda_results.txt
miranda neg_176_mirna.fas neg_176_target.fas -strict > neg_176_miranda_results.txt
miranda neg_177_mirna.fas neg_177_target.fas -strict > neg_177_miranda_results.txt
miranda neg_178_mirna.fas neg_178_target.fas -strict > neg_178_miranda_results.txt
miranda neg_179_mirna.fas neg_179_target.fas -strict > neg_179_miranda_results.txt
miranda neg_180_mirna.fas neg_180_target.fas -strict > neg_180_miranda_results.txt
miranda neg_181_mirna.fas neg_181_target.fas -strict > neg_181_miranda_results.txt
miranda neg_182_mirna.fas neg_182_target.fas -strict > neg_182_miranda_results.txt
miranda neg_183_mirna.fas neg_183_target.fas -strict > neg_183_miranda_results.txt
miranda neg_184_mirna.fas neg_184_target.fas -strict > neg_184_miranda_results.txt
miranda neg_185_mirna.fas neg_185_target.fas -strict > neg_185_miranda_results.txt
miranda neg_186_mirna.fas neg_186_target.fas -strict > neg_186_miranda_results.txt
miranda neg_187_mirna.fas neg_187_target.fas -strict > neg_187_miranda_results.txt
miranda neg_188_mirna.fas neg_188_target.fas -strict > neg_188_miranda_results.txt
miranda neg_189_mirna.fas neg_189_target.fas -strict > neg_189_miranda_results.txt
miranda neg_190_mirna.fas neg_190_target.fas -strict > neg_190_miranda_results.txt
miranda neg_191_mirna.fas neg_191_target.fas -strict > neg_191_miranda_results.txt
miranda neg_192_mirna.fas neg_192_target.fas -strict > neg_192_miranda_results.txt
miranda neg_193_mirna.fas neg_193_target.fas -strict > neg_193_miranda_results.txt
miranda neg_194_mirna.fas neg_194_target.fas -strict > neg_194_miranda_results.txt
miranda neg_195_mirna.fas neg_195_target.fas -strict > neg_195_miranda_results.txt
miranda neg_196_mirna.fas neg_196_target.fas -strict > neg_196_miranda_results.txt
miranda neg_197_mirna.fas neg_197_target.fas -strict > neg_197_miranda_results.txt
miranda neg_198_mirna.fas neg_198_target.fas -strict > neg_198_miranda_results.txt
miranda neg_199_mirna.fas neg_199_target.fas -strict > neg_199_miranda_results.txt
miranda neg_200_mirna.fas neg_200_target.fas -strict > neg_200_miranda_results.txt
miranda neg_201_mirna.fas neg_201_target.fas -strict > neg_201_miranda_results.txt
miranda neg_202_mirna.fas neg_202_target.fas -strict > neg_202_miranda_results.txt
miranda neg_203_mirna.fas neg_203_target.fas -strict > neg_203_miranda_results.txt
miranda neg_204_mirna.fas neg_204_target.fas -strict > neg_204_miranda_results.txt
miranda neg_205_mirna.fas neg_205_target.fas -strict > neg_205_miranda_results.txt
miranda neg_206_mirna.fas neg_206_target.fas -strict > neg_206_miranda_results.txt
miranda neg_207_mirna.fas neg_207_target.fas -strict > neg_207_miranda_results.txt
miranda neg_208_mirna.fas neg_208_target.fas -strict > neg_208_miranda_results.txt
miranda neg_209_mirna.fas neg_209_target.fas -strict > neg_209_miranda_results.txt
miranda neg_210_mirna.fas neg_210_target.fas -strict > neg_210_miranda_results.txt
miranda neg_211_mirna.fas neg_211_target.fas -strict > neg_211_miranda_results.txt
miranda neg_212_mirna.fas neg_212_target.fas -strict > neg_212_miranda_results.txt
miranda neg_213_mirna.fas neg_213_target.fas -strict > neg_213_miranda_results.txt
miranda neg_214_mirna.fas neg_214_target.fas -strict > neg_214_miranda_results.txt
miranda neg_215_mirna.fas neg_215_target.fas -strict > neg_215_miranda_results.txt
miranda neg_216_mirna.fas neg_216_target.fas -strict > neg_216_miranda_results.txt
miranda neg_217_mirna.fas neg_217_target.fas -strict > neg_217_miranda_results.txt
miranda neg_218_mirna.fas neg_218_target.fas -strict > neg_218_miranda_results.txt
miranda neg_219_mirna.fas neg_219_target.fas -strict > neg_219_miranda_results.txt
miranda neg_220_mirna.fas neg_220_target.fas -strict > neg_220_miranda_results.txt
miranda neg_221_mirna.fas neg_221_target.fas -strict > neg_221_miranda_results.txt
miranda neg_222_mirna.fas neg_222_target.fas -strict > neg_222_miranda_results.txt
miranda neg_223_mirna.fas neg_223_target.fas -strict > neg_223_miranda_results.txt
miranda neg_224_mirna.fas neg_224_target.fas -strict > neg_224_miranda_results.txt
miranda neg_225_mirna.fas neg_225_target.fas -strict > neg_225_miranda_results.txt
miranda neg_226_mirna.fas neg_226_target.fas -strict > neg_226_miranda_results.txt
miranda neg_227_mirna.fas neg_227_target.fas -strict > neg_227_miranda_results.txt
miranda neg_228_mirna.fas neg_228_target.fas -strict > neg_228_miranda_results.txt
miranda neg_229_mirna.fas neg_229_target.fas -strict > neg_229_miranda_results.txt
miranda neg_230_mirna.fas neg_230_target.fas -strict > neg_230_miranda_results.txt
miranda neg_231_mirna.fas neg_231_target.fas -strict > neg_231_miranda_results.txt
miranda neg_232_mirna.fas neg_232_target.fas -strict > neg_232_miranda_results.txt
miranda neg_233_mirna.fas neg_233_target.fas -strict > neg_233_miranda_results.txt
miranda neg_234_mirna.fas neg_234_target.fas -strict > neg_234_miranda_results.txt
miranda neg_235_mirna.fas neg_235_target.fas -strict > neg_235_miranda_results.txt
miranda neg_236_mirna.fas neg_236_target.fas -strict > neg_236_miranda_results.txt
miranda neg_237_mirna.fas neg_237_target.fas -strict > neg_237_miranda_results.txt
miranda neg_238_mirna.fas neg_238_target.fas -strict > neg_238_miranda_results.txt
miranda neg_239_mirna.fas neg_239_target.fas -strict > neg_239_miranda_results.txt
miranda neg_240_mirna.fas neg_240_target.fas -strict > neg_240_miranda_results.txt
miranda neg_241_mirna.fas neg_241_target.fas -strict > neg_241_miranda_results.txt
miranda neg_242_mirna.fas neg_242_target.fas -strict > neg_242_miranda_results.txt
miranda neg_243_mirna.fas neg_243_target.fas -strict > neg_243_miranda_results.txt
miranda neg_244_mirna.fas neg_244_target.fas -strict > neg_244_miranda_results.txt
miranda neg_245_mirna.fas neg_245_target.fas -strict > neg_245_miranda_results.txt
miranda neg_246_mirna.fas neg_246_target.fas -strict > neg_246_miranda_results.txt
miranda neg_247_mirna.fas neg_247_target.fas -strict > neg_247_miranda_results.txt
miranda neg_248_mirna.fas neg_248_target.fas -strict > neg_248_miranda_results.txt
miranda neg_249_mirna.fas neg_249_target.fas -strict > neg_249_miranda_results.txt
miranda neg_250_mirna.fas neg_250_target.fas -strict > neg_250_miranda_results.txt
miranda neg_251_mirna.fas neg_251_target.fas -strict > neg_251_miranda_results.txt
miranda neg_252_mirna.fas neg_252_target.fas -strict > neg_252_miranda_results.txt
miranda neg_253_mirna.fas neg_253_target.fas -strict > neg_253_miranda_results.txt
miranda neg_254_mirna.fas neg_254_target.fas -strict > neg_254_miranda_results.txt
miranda neg_255_mirna.fas neg_255_target.fas -strict > neg_255_miranda_results.txt
miranda neg_256_mirna.fas neg_256_target.fas -strict > neg_256_miranda_results.txt
miranda neg_257_mirna.fas neg_257_target.fas -strict > neg_257_miranda_results.txt
miranda neg_258_mirna.fas neg_258_target.fas -strict > neg_258_miranda_results.txt
miranda neg_259_mirna.fas neg_259_target.fas -strict > neg_259_miranda_results.txt
miranda neg_260_mirna.fas neg_260_target.fas -strict > neg_260_miranda_results.txt
miranda neg_261_mirna.fas neg_261_target.fas -strict > neg_261_miranda_results.txt
miranda neg_262_mirna.fas neg_262_target.fas -strict > neg_262_miranda_results.txt
miranda neg_263_mirna.fas neg_263_target.fas -strict > neg_263_miranda_results.txt
miranda neg_264_mirna.fas neg_264_target.fas -strict > neg_264_miranda_results.txt
miranda neg_265_mirna.fas neg_265_target.fas -strict > neg_265_miranda_results.txt
miranda neg_266_mirna.fas neg_266_target.fas -strict > neg_266_miranda_results.txt
miranda neg_267_mirna.fas neg_267_target.fas -strict > neg_267_miranda_results.txt
miranda neg_268_mirna.fas neg_268_target.fas -strict > neg_268_miranda_results.txt
miranda neg_269_mirna.fas neg_269_target.fas -strict > neg_269_miranda_results.txt
miranda neg_270_mirna.fas neg_270_target.fas -strict > neg_270_miranda_results.txt
miranda neg_271_mirna.fas neg_271_target.fas -strict > neg_271_miranda_results.txt
miranda neg_272_mirna.fas neg_272_target.fas -strict > neg_272_miranda_results.txt
miranda neg_273_mirna.fas neg_273_target.fas -strict > neg_273_miranda_results.txt
miranda neg_274_mirna.fas neg_274_target.fas -strict > neg_274_miranda_results.txt
miranda neg_275_mirna.fas neg_275_target.fas -strict > neg_275_miranda_results.txt
miranda neg_276_mirna.fas neg_276_target.fas -strict > neg_276_miranda_results.txt
miranda neg_277_mirna.fas neg_277_target.fas -strict > neg_277_miranda_results.txt
miranda neg_278_mirna.fas neg_278_target.fas -strict > neg_278_miranda_results.txt
miranda neg_279_mirna.fas neg_279_target.fas -strict > neg_279_miranda_results.txt
miranda neg_280_mirna.fas neg_280_target.fas -strict > neg_280_miranda_results.txt
miranda neg_281_mirna.fas neg_281_target.fas -strict > neg_281_miranda_results.txt
miranda neg_282_mirna.fas neg_282_target.fas -strict > neg_282_miranda_results.txt
miranda neg_283_mirna.fas neg_283_target.fas -strict > neg_283_miranda_results.txt
miranda neg_284_mirna.fas neg_284_target.fas -strict > neg_284_miranda_results.txt
miranda neg_285_mirna.fas neg_285_target.fas -strict > neg_285_miranda_results.txt
miranda neg_286_mirna.fas neg_286_target.fas -strict > neg_286_miranda_results.txt
miranda neg_287_mirna.fas neg_287_target.fas -strict > neg_287_miranda_results.txt
miranda neg_288_mirna.fas neg_288_target.fas -strict > neg_288_miranda_results.txt
miranda neg_289_mirna.fas neg_289_target.fas -strict > neg_289_miranda_results.txt
miranda pos_1_mirna.fas pos_1_target.fas -strict > pos_1_miranda_results.txt
miranda pos_2_mirna.fas pos_2_target.fas -strict > pos_2_miranda_results.txt
miranda pos_3_mirna.fas pos_3_target.fas -strict > pos_3_miranda_results.txt
miranda pos_4_mirna.fas pos_4_target.fas -strict > pos_4_miranda_results.txt
miranda pos_5_mirna.fas pos_5_target.fas -strict > pos_5_miranda_results.txt
miranda pos_6_mirna.fas pos_6_target.fas -strict > pos_6_miranda_results.txt
miranda pos_7_mirna.fas pos_7_target.fas -strict > pos_7_miranda_results.txt
miranda pos_8_mirna.fas pos_8_target.fas -strict > pos_8_miranda_results.txt
miranda pos_9_mirna.fas pos_9_target.fas -strict > pos_9_miranda_results.txt
miranda pos_10_mirna.fas pos_10_target.fas -strict > pos_10_miranda_results.txt
miranda pos_11_mirna.fas pos_11_target.fas -strict > pos_11_miranda_results.txt
miranda pos_12_mirna.fas pos_12_target.fas -strict > pos_12_miranda_results.txt
miranda pos_13_mirna.fas pos_13_target.fas -strict > pos_13_miranda_results.txt
miranda pos_14_mirna.fas pos_14_target.fas -strict > pos_14_miranda_results.txt
miranda pos_15_mirna.fas pos_15_target.fas -strict > pos_15_miranda_results.txt
miranda pos_16_mirna.fas pos_16_target.fas -strict > pos_16_miranda_results.txt
miranda pos_17_mirna.fas pos_17_target.fas -strict > pos_17_miranda_results.txt
miranda pos_18_mirna.fas pos_18_target.fas -strict > pos_18_miranda_results.txt
miranda pos_19_mirna.fas pos_19_target.fas -strict > pos_19_miranda_results.txt
miranda pos_20_mirna.fas pos_20_target.fas -strict > pos_20_miranda_results.txt
miranda pos_21_mirna.fas pos_21_target.fas -strict > pos_21_miranda_results.txt
miranda pos_22_mirna.fas pos_22_target.fas -strict > pos_22_miranda_results.txt
miranda pos_23_mirna.fas pos_23_target.fas -strict > pos_23_miranda_results.txt
miranda pos_24_mirna.fas pos_24_target.fas -strict > pos_24_miranda_results.txt
miranda pos_25_mirna.fas pos_25_target.fas -strict > pos_25_miranda_results.txt
miranda pos_26_mirna.fas pos_26_target.fas -strict > pos_26_miranda_results.txt
miranda pos_27_mirna.fas pos_27_target.fas -strict > pos_27_miranda_results.txt
miranda pos_28_mirna.fas pos_28_target.fas -strict > pos_28_miranda_results.txt
miranda pos_29_mirna.fas pos_29_target.fas -strict > pos_29_miranda_results.txt
miranda pos_30_mirna.fas pos_30_target.fas -strict > pos_30_miranda_results.txt
miranda pos_31_mirna.fas pos_31_target.fas -strict > pos_31_miranda_results.txt
miranda pos_32_mirna.fas pos_32_target.fas -strict > pos_32_miranda_results.txt
miranda pos_33_mirna.fas pos_33_target.fas -strict > pos_33_miranda_results.txt
miranda pos_34_mirna.fas pos_34_target.fas -strict > pos_34_miranda_results.txt
miranda pos_35_mirna.fas pos_35_target.fas -strict > pos_35_miranda_results.txt
miranda pos_36_mirna.fas pos_36_target.fas -strict > pos_36_miranda_results.txt
miranda pos_37_mirna.fas pos_37_target.fas -strict > pos_37_miranda_results.txt
miranda pos_38_mirna.fas pos_38_target.fas -strict > pos_38_miranda_results.txt
miranda pos_39_mirna.fas pos_39_target.fas -strict > pos_39_miranda_results.txt
miranda pos_40_mirna.fas pos_40_target.fas -strict > pos_40_miranda_results.txt
miranda pos_41_mirna.fas pos_41_target.fas -strict > pos_41_miranda_results.txt
miranda pos_42_mirna.fas pos_42_target.fas -strict > pos_42_miranda_results.txt
miranda pos_43_mirna.fas pos_43_target.fas -strict > pos_43_miranda_results.txt
miranda pos_44_mirna.fas pos_44_target.fas -strict > pos_44_miranda_results.txt
miranda pos_45_mirna.fas pos_45_target.fas -strict > pos_45_miranda_results.txt
miranda pos_46_mirna.fas pos_46_target.fas -strict > pos_46_miranda_results.txt
miranda pos_47_mirna.fas pos_47_target.fas -strict > pos_47_miranda_results.txt
miranda pos_48_mirna.fas pos_48_target.fas -strict > pos_48_miranda_results.txt
miranda pos_49_mirna.fas pos_49_target.fas -strict > pos_49_miranda_results.txt
miranda pos_50_mirna.fas pos_50_target.fas -strict > pos_50_miranda_results.txt
miranda pos_51_mirna.fas pos_51_target.fas -strict > pos_51_miranda_results.txt
miranda pos_52_mirna.fas pos_52_target.fas -strict > pos_52_miranda_results.txt
miranda pos_53_mirna.fas pos_53_target.fas -strict > pos_53_miranda_results.txt
miranda pos_54_mirna.fas pos_54_target.fas -strict > pos_54_miranda_results.txt
miranda pos_55_mirna.fas pos_55_target.fas -strict > pos_55_miranda_results.txt
miranda pos_56_mirna.fas pos_56_target.fas -strict > pos_56_miranda_results.txt
miranda pos_57_mirna.fas pos_57_target.fas -strict > pos_57_miranda_results.txt
miranda pos_58_mirna.fas pos_58_target.fas -strict > pos_58_miranda_results.txt
miranda pos_59_mirna.fas pos_59_target.fas -strict > pos_59_miranda_results.txt
miranda pos_60_mirna.fas pos_60_target.fas -strict > pos_60_miranda_results.txt
miranda pos_61_mirna.fas pos_61_target.fas -strict > pos_61_miranda_results.txt
miranda pos_62_mirna.fas pos_62_target.fas -strict > pos_62_miranda_results.txt
miranda pos_63_mirna.fas pos_63_target.fas -strict > pos_63_miranda_results.txt
miranda pos_64_mirna.fas pos_64_target.fas -strict > pos_64_miranda_results.txt
miranda pos_65_mirna.fas pos_65_target.fas -strict > pos_65_miranda_results.txt
miranda pos_66_mirna.fas pos_66_target.fas -strict > pos_66_miranda_results.txt
miranda pos_67_mirna.fas pos_67_target.fas -strict > pos_67_miranda_results.txt
miranda pos_68_mirna.fas pos_68_target.fas -strict > pos_68_miranda_results.txt
miranda pos_69_mirna.fas pos_69_target.fas -strict > pos_69_miranda_results.txt
miranda pos_70_mirna.fas pos_70_target.fas -strict > pos_70_miranda_results.txt
miranda pos_71_mirna.fas pos_71_target.fas -strict > pos_71_miranda_results.txt
miranda pos_72_mirna.fas pos_72_target.fas -strict > pos_72_miranda_results.txt
miranda pos_73_mirna.fas pos_73_target.fas -strict > pos_73_miranda_results.txt
miranda pos_74_mirna.fas pos_74_target.fas -strict > pos_74_miranda_results.txt
miranda pos_75_mirna.fas pos_75_target.fas -strict > pos_75_miranda_results.txt
miranda pos_76_mirna.fas pos_76_target.fas -strict > pos_76_miranda_results.txt
miranda pos_77_mirna.fas pos_77_target.fas -strict > pos_77_miranda_results.txt
miranda pos_78_mirna.fas pos_78_target.fas -strict > pos_78_miranda_results.txt
miranda pos_79_mirna.fas pos_79_target.fas -strict > pos_79_miranda_results.txt
miranda pos_80_mirna.fas pos_80_target.fas -strict > pos_80_miranda_results.txt
miranda pos_81_mirna.fas pos_81_target.fas -strict > pos_81_miranda_results.txt
miranda pos_82_mirna.fas pos_82_target.fas -strict > pos_82_miranda_results.txt
miranda pos_83_mirna.fas pos_83_target.fas -strict > pos_83_miranda_results.txt
miranda pos_84_mirna.fas pos_84_target.fas -strict > pos_84_miranda_results.txt
miranda pos_85_mirna.fas pos_85_target.fas -strict > pos_85_miranda_results.txt
miranda pos_86_mirna.fas pos_86_target.fas -strict > pos_86_miranda_results.txt
miranda pos_87_mirna.fas pos_87_target.fas -strict > pos_87_miranda_results.txt
miranda pos_88_mirna.fas pos_88_target.fas -strict > pos_88_miranda_results.txt
miranda pos_89_mirna.fas pos_89_target.fas -strict > pos_89_miranda_results.txt
miranda pos_90_mirna.fas pos_90_target.fas -strict > pos_90_miranda_results.txt
miranda pos_91_mirna.fas pos_91_target.fas -strict > pos_91_miranda_results.txt
miranda pos_92_mirna.fas pos_92_target.fas -strict > pos_92_miranda_results.txt
miranda pos_93_mirna.fas pos_93_target.fas -strict > pos_93_miranda_results.txt
miranda pos_94_mirna.fas pos_94_target.fas -strict > pos_94_miranda_results.txt
miranda pos_95_mirna.fas pos_95_target.fas -strict > pos_95_miranda_results.txt
miranda pos_96_mirna.fas pos_96_target.fas -strict > pos_96_miranda_results.txt
miranda pos_97_mirna.fas pos_97_target.fas -strict > pos_97_miranda_results.txt
miranda pos_98_mirna.fas pos_98_target.fas -strict > pos_98_miranda_results.txt
miranda pos_99_mirna.fas pos_99_target.fas -strict > pos_99_miranda_results.txt
miranda pos_100_mirna.fas pos_100_target.fas -strict > pos_100_miranda_results.txt
miranda pos_101_mirna.fas pos_101_target.fas -strict > pos_101_miranda_results.txt
miranda pos_102_mirna.fas pos_102_target.fas -strict > pos_102_miranda_results.txt
miranda pos_103_mirna.fas pos_103_target.fas -strict > pos_103_miranda_results.txt
miranda pos_104_mirna.fas pos_104_target.fas -strict > pos_104_miranda_results.txt
miranda pos_105_mirna.fas pos_105_target.fas -strict > pos_105_miranda_results.txt
miranda pos_106_mirna.fas pos_106_target.fas -strict > pos_106_miranda_results.txt
miranda pos_107_mirna.fas pos_107_target.fas -strict > pos_107_miranda_results.txt
miranda pos_108_mirna.fas pos_108_target.fas -strict > pos_108_miranda_results.txt
miranda pos_109_mirna.fas pos_109_target.fas -strict > pos_109_miranda_results.txt
miranda pos_110_mirna.fas pos_110_target.fas -strict > pos_110_miranda_results.txt
miranda pos_111_mirna.fas pos_111_target.fas -strict > pos_111_miranda_results.txt
miranda pos_112_mirna.fas pos_112_target.fas -strict > pos_112_miranda_results.txt
miranda pos_113_mirna.fas pos_113_target.fas -strict > pos_113_miranda_results.txt
miranda pos_114_mirna.fas pos_114_target.fas -strict > pos_114_miranda_results.txt
miranda pos_115_mirna.fas pos_115_target.fas -strict > pos_115_miranda_results.txt
miranda pos_116_mirna.fas pos_116_target.fas -strict > pos_116_miranda_results.txt
miranda pos_117_mirna.fas pos_117_target.fas -strict > pos_117_miranda_results.txt
miranda pos_118_mirna.fas pos_118_target.fas -strict > pos_118_miranda_results.txt
miranda pos_119_mirna.fas pos_119_target.fas -strict > pos_119_miranda_results.txt
miranda pos_120_mirna.fas pos_120_target.fas -strict > pos_120_miranda_results.txt
miranda pos_121_mirna.fas pos_121_target.fas -strict > pos_121_miranda_results.txt
miranda pos_122_mirna.fas pos_122_target.fas -strict > pos_122_miranda_results.txt
miranda pos_123_mirna.fas pos_123_target.fas -strict > pos_123_miranda_results.txt
miranda pos_124_mirna.fas pos_124_target.fas -strict > pos_124_miranda_results.txt
miranda pos_125_mirna.fas pos_125_target.fas -strict > pos_125_miranda_results.txt
miranda pos_126_mirna.fas pos_126_target.fas -strict > pos_126_miranda_results.txt
miranda pos_127_mirna.fas pos_127_target.fas -strict > pos_127_miranda_results.txt
miranda pos_128_mirna.fas pos_128_target.fas -strict > pos_128_miranda_results.txt
miranda pos_129_mirna.fas pos_129_target.fas -strict > pos_129_miranda_results.txt
miranda pos_130_mirna.fas pos_130_target.fas -strict > pos_130_miranda_results.txt
miranda pos_131_mirna.fas pos_131_target.fas -strict > pos_131_miranda_results.txt
miranda pos_132_mirna.fas pos_132_target.fas -strict > pos_132_miranda_results.txt
miranda pos_133_mirna.fas pos_133_target.fas -strict > pos_133_miranda_results.txt
miranda pos_134_mirna.fas pos_134_target.fas -strict > pos_134_miranda_results.txt
miranda pos_135_mirna.fas pos_135_target.fas -strict > pos_135_miranda_results.txt
miranda pos_136_mirna.fas pos_136_target.fas -strict > pos_136_miranda_results.txt
miranda pos_137_mirna.fas pos_137_target.fas -strict > pos_137_miranda_results.txt
miranda pos_138_mirna.fas pos_138_target.fas -strict > pos_138_miranda_results.txt
miranda pos_139_mirna.fas pos_139_target.fas -strict > pos_139_miranda_results.txt
miranda pos_140_mirna.fas pos_140_target.fas -strict > pos_140_miranda_results.txt
miranda pos_141_mirna.fas pos_141_target.fas -strict > pos_141_miranda_results.txt
miranda pos_142_mirna.fas pos_142_target.fas -strict > pos_142_miranda_results.txt
miranda pos_143_mirna.fas pos_143_target.fas -strict > pos_143_miranda_results.txt
miranda pos_144_mirna.fas pos_144_target.fas -strict > pos_144_miranda_results.txt
miranda pos_145_mirna.fas pos_145_target.fas -strict > pos_145_miranda_results.txt
miranda pos_146_mirna.fas pos_146_target.fas -strict > pos_146_miranda_results.txt
miranda pos_147_mirna.fas pos_147_target.fas -strict > pos_147_miranda_results.txt
miranda pos_148_mirna.fas pos_148_target.fas -strict > pos_148_miranda_results.txt
miranda pos_149_mirna.fas pos_149_target.fas -strict > pos_149_miranda_results.txt
miranda pos_150_mirna.fas pos_150_target.fas -strict > pos_150_miranda_results.txt
miranda pos_151_mirna.fas pos_151_target.fas -strict > pos_151_miranda_results.txt
miranda pos_152_mirna.fas pos_152_target.fas -strict > pos_152_miranda_results.txt
miranda pos_153_mirna.fas pos_153_target.fas -strict > pos_153_miranda_results.txt
miranda pos_154_mirna.fas pos_154_target.fas -strict > pos_154_miranda_results.txt
miranda pos_155_mirna.fas pos_155_target.fas -strict > pos_155_miranda_results.txt
miranda pos_156_mirna.fas pos_156_target.fas -strict > pos_156_miranda_results.txt
miranda pos_157_mirna.fas pos_157_target.fas -strict > pos_157_miranda_results.txt
miranda pos_158_mirna.fas pos_158_target.fas -strict > pos_158_miranda_results.txt
miranda pos_159_mirna.fas pos_159_target.fas -strict > pos_159_miranda_results.txt
miranda pos_160_mirna.fas pos_160_target.fas -strict > pos_160_miranda_results.txt
miranda pos_161_mirna.fas pos_161_target.fas -strict > pos_161_miranda_results.txt
miranda pos_162_mirna.fas pos_162_target.fas -strict > pos_162_miranda_results.txt
miranda pos_163_mirna.fas pos_163_target.fas -strict > pos_163_miranda_results.txt
miranda pos_164_mirna.fas pos_164_target.fas -strict > pos_164_miranda_results.txt
miranda pos_165_mirna.fas pos_165_target.fas -strict > pos_165_miranda_results.txt
miranda pos_166_mirna.fas pos_166_target.fas -strict > pos_166_miranda_results.txt
miranda pos_167_mirna.fas pos_167_target.fas -strict > pos_167_miranda_results.txt
miranda pos_168_mirna.fas pos_168_target.fas -strict > pos_168_miranda_results.txt
miranda pos_169_mirna.fas pos_169_target.fas -strict > pos_169_miranda_results.txt
miranda pos_170_mirna.fas pos_170_target.fas -strict > pos_170_miranda_results.txt
miranda pos_171_mirna.fas pos_171_target.fas -strict > pos_171_miranda_results.txt
miranda pos_172_mirna.fas pos_172_target.fas -strict > pos_172_miranda_results.txt
miranda pos_173_mirna.fas pos_173_target.fas -strict > pos_173_miranda_results.txt
miranda pos_174_mirna.fas pos_174_target.fas -strict > pos_174_miranda_results.txt
miranda pos_175_mirna.fas pos_175_target.fas -strict > pos_175_miranda_results.txt
miranda pos_176_mirna.fas pos_176_target.fas -strict > pos_176_miranda_results.txt
miranda pos_177_mirna.fas pos_177_target.fas -strict > pos_177_miranda_results.txt
miranda pos_178_mirna.fas pos_178_target.fas -strict > pos_178_miranda_results.txt
miranda pos_179_mirna.fas pos_179_target.fas -strict > pos_179_miranda_results.txt
miranda pos_180_mirna.fas pos_180_target.fas -strict > pos_180_miranda_results.txt
miranda pos_181_mirna.fas pos_181_target.fas -strict > pos_181_miranda_results.txt
miranda pos_182_mirna.fas pos_182_target.fas -strict > pos_182_miranda_results.txt
miranda pos_183_mirna.fas pos_183_target.fas -strict > pos_183_miranda_results.txt
miranda pos_184_mirna.fas pos_184_target.fas -strict > pos_184_miranda_results.txt
miranda pos_185_mirna.fas pos_185_target.fas -strict > pos_185_miranda_results.txt
miranda pos_186_mirna.fas pos_186_target.fas -strict > pos_186_miranda_results.txt
miranda pos_187_mirna.fas pos_187_target.fas -strict > pos_187_miranda_results.txt
miranda pos_188_mirna.fas pos_188_target.fas -strict > pos_188_miranda_results.txt
miranda pos_189_mirna.fas pos_189_target.fas -strict > pos_189_miranda_results.txt
miranda pos_190_mirna.fas pos_190_target.fas -strict > pos_190_miranda_results.txt
miranda pos_191_mirna.fas pos_191_target.fas -strict > pos_191_miranda_results.txt
miranda pos_192_mirna.fas pos_192_target.fas -strict > pos_192_miranda_results.txt
miranda pos_193_mirna.fas pos_193_target.fas -strict > pos_193_miranda_results.txt
miranda pos_194_mirna.fas pos_194_target.fas -strict > pos_194_miranda_results.txt
miranda pos_195_mirna.fas pos_195_target.fas -strict > pos_195_miranda_results.txt
miranda pos_196_mirna.fas pos_196_target.fas -strict > pos_196_miranda_results.txt
miranda pos_197_mirna.fas pos_197_target.fas -strict > pos_197_miranda_results.txt
miranda pos_198_mirna.fas pos_198_target.fas -strict > pos_198_miranda_results.txt
miranda pos_199_mirna.fas pos_199_target.fas -strict > pos_199_miranda_results.txt
miranda pos_200_mirna.fas pos_200_target.fas -strict > pos_200_miranda_results.txt
miranda pos_201_mirna.fas pos_201_target.fas -strict > pos_201_miranda_results.txt
miranda pos_202_mirna.fas pos_202_target.fas -strict > pos_202_miranda_results.txt
miranda pos_203_mirna.fas pos_203_target.fas -strict > pos_203_miranda_results.txt
miranda pos_204_mirna.fas pos_204_target.fas -strict > pos_204_miranda_results.txt
miranda pos_205_mirna.fas pos_205_target.fas -strict > pos_205_miranda_results.txt
miranda pos_206_mirna.fas pos_206_target.fas -strict > pos_206_miranda_results.txt
miranda pos_207_mirna.fas pos_207_target.fas -strict > pos_207_miranda_results.txt
miranda pos_208_mirna.fas pos_208_target.fas -strict > pos_208_miranda_results.txt
miranda pos_209_mirna.fas pos_209_target.fas -strict > pos_209_miranda_results.txt
miranda pos_210_mirna.fas pos_210_target.fas -strict > pos_210_miranda_results.txt
miranda pos_211_mirna.fas pos_211_target.fas -strict > pos_211_miranda_results.txt
miranda pos_212_mirna.fas pos_212_target.fas -strict > pos_212_miranda_results.txt
miranda pos_213_mirna.fas pos_213_target.fas -strict > pos_213_miranda_results.txt
miranda pos_214_mirna.fas pos_214_target.fas -strict > pos_214_miranda_results.txt
miranda pos_215_mirna.fas pos_215_target.fas -strict > pos_215_miranda_results.txt
miranda pos_216_mirna.fas pos_216_target.fas -strict > pos_216_miranda_results.txt
miranda pos_217_mirna.fas pos_217_target.fas -strict > pos_217_miranda_results.txt
miranda pos_218_mirna.fas pos_218_target.fas -strict > pos_218_miranda_results.txt
miranda pos_219_mirna.fas pos_219_target.fas -strict > pos_219_miranda_results.txt
miranda pos_220_mirna.fas pos_220_target.fas -strict > pos_220_miranda_results.txt
miranda pos_221_mirna.fas pos_221_target.fas -strict > pos_221_miranda_results.txt
miranda pos_222_mirna.fas pos_222_target.fas -strict > pos_222_miranda_results.txt
miranda pos_223_mirna.fas pos_223_target.fas -strict > pos_223_miranda_results.txt
miranda pos_224_mirna.fas pos_224_target.fas -strict > pos_224_miranda_results.txt
miranda pos_225_mirna.fas pos_225_target.fas -strict > pos_225_miranda_results.txt
miranda pos_226_mirna.fas pos_226_target.fas -strict > pos_226_miranda_results.txt
miranda pos_227_mirna.fas pos_227_target.fas -strict > pos_227_miranda_results.txt
miranda pos_228_mirna.fas pos_228_target.fas -strict > pos_228_miranda_results.txt
miranda pos_229_mirna.fas pos_229_target.fas -strict > pos_229_miranda_results.txt
miranda pos_230_mirna.fas pos_230_target.fas -strict > pos_230_miranda_results.txt
miranda pos_231_mirna.fas pos_231_target.fas -strict > pos_231_miranda_results.txt
miranda pos_232_mirna.fas pos_232_target.fas -strict > pos_232_miranda_results.txt
miranda pos_233_mirna.fas pos_233_target.fas -strict > pos_233_miranda_results.txt
miranda pos_234_mirna.fas pos_234_target.fas -strict > pos_234_miranda_results.txt
miranda pos_235_mirna.fas pos_235_target.fas -strict > pos_235_miranda_results.txt
miranda pos_236_mirna.fas pos_236_target.fas -strict > pos_236_miranda_results.txt
miranda pos_237_mirna.fas pos_237_target.fas -strict > pos_237_miranda_results.txt
miranda pos_238_mirna.fas pos_238_target.fas -strict > pos_238_miranda_results.txt
miranda pos_239_mirna.fas pos_239_target.fas -strict > pos_239_miranda_results.txt
miranda pos_240_mirna.fas pos_240_target.fas -strict > pos_240_miranda_results.txt
miranda pos_241_mirna.fas pos_241_target.fas -strict > pos_241_miranda_results.txt
miranda pos_242_mirna.fas pos_242_target.fas -strict > pos_242_miranda_results.txt
miranda pos_243_mirna.fas pos_243_target.fas -strict > pos_243_miranda_results.txt
miranda pos_244_mirna.fas pos_244_target.fas -strict > pos_244_miranda_results.txt
miranda pos_245_mirna.fas pos_245_target.fas -strict > pos_245_miranda_results.txt
miranda pos_246_mirna.fas pos_246_target.fas -strict > pos_246_miranda_results.txt
miranda pos_247_mirna.fas pos_247_target.fas -strict > pos_247_miranda_results.txt
miranda pos_248_mirna.fas pos_248_target.fas -strict > pos_248_miranda_results.txt
miranda pos_249_mirna.fas pos_249_target.fas -strict > pos_249_miranda_results.txt
miranda pos_250_mirna.fas pos_250_target.fas -strict > pos_250_miranda_results.txt
miranda pos_251_mirna.fas pos_251_target.fas -strict > pos_251_miranda_results.txt
miranda pos_252_mirna.fas pos_252_target.fas -strict > pos_252_miranda_results.txt
miranda pos_253_mirna.fas pos_253_target.fas -strict > pos_253_miranda_results.txt
miranda pos_254_mirna.fas pos_254_target.fas -strict > pos_254_miranda_results.txt
miranda pos_255_mirna.fas pos_255_target.fas -strict > pos_255_miranda_results.txt
miranda pos_256_mirna.fas pos_256_target.fas -strict > pos_256_miranda_results.txt
miranda pos_257_mirna.fas pos_257_target.fas -strict > pos_257_miranda_results.txt
miranda pos_258_mirna.fas pos_258_target.fas -strict > pos_258_miranda_results.txt
miranda pos_259_mirna.fas pos_259_target.fas -strict > pos_259_miranda_results.txt
miranda pos_260_mirna.fas pos_260_target.fas -strict > pos_260_miranda_results.txt
miranda pos_261_mirna.fas pos_261_target.fas -strict > pos_261_miranda_results.txt
miranda pos_262_mirna.fas pos_262_target.fas -strict > pos_262_miranda_results.txt
miranda pos_263_mirna.fas pos_263_target.fas -strict > pos_263_miranda_results.txt
miranda pos_264_mirna.fas pos_264_target.fas -strict > pos_264_miranda_results.txt
miranda pos_265_mirna.fas pos_265_target.fas -strict > pos_265_miranda_results.txt
miranda pos_266_mirna.fas pos_266_target.fas -strict > pos_266_miranda_results.txt
miranda pos_267_mirna.fas pos_267_target.fas -strict > pos_267_miranda_results.txt
miranda pos_268_mirna.fas pos_268_target.fas -strict > pos_268_miranda_results.txt
miranda pos_269_mirna.fas pos_269_target.fas -strict > pos_269_miranda_results.txt
miranda pos_270_mirna.fas pos_270_target.fas -strict > pos_270_miranda_results.txt
miranda pos_271_mirna.fas pos_271_target.fas -strict > pos_271_miranda_results.txt
miranda pos_272_mirna.fas pos_272_target.fas -strict > pos_272_miranda_results.txt
miranda pos_273_mirna.fas pos_273_target.fas -strict > pos_273_miranda_results.txt
miranda pos_274_mirna.fas pos_274_target.fas -strict > pos_274_miranda_results.txt
miranda pos_275_mirna.fas pos_275_target.fas -strict > pos_275_miranda_results.txt
miranda pos_276_mirna.fas pos_276_target.fas -strict > pos_276_miranda_results.txt
miranda pos_277_mirna.fas pos_277_target.fas -strict > pos_277_miranda_results.txt
miranda pos_278_mirna.fas pos_278_target.fas -strict > pos_278_miranda_results.txt
miranda pos_279_mirna.fas pos_279_target.fas -strict > pos_279_miranda_results.txt
miranda pos_280_mirna.fas pos_280_target.fas -strict > pos_280_miranda_results.txt
miranda pos_281_mirna.fas pos_281_target.fas -strict > pos_281_miranda_results.txt
miranda pos_282_mirna.fas pos_282_target.fas -strict > pos_282_miranda_results.txt
miranda pos_283_mirna.fas pos_283_target.fas -strict > pos_283_miranda_results.txt
miranda pos_284_mirna.fas pos_284_target.fas -strict > pos_284_miranda_results.txt
miranda pos_285_mirna.fas pos_285_target.fas -strict > pos_285_miranda_results.txt
miranda pos_286_mirna.fas pos_286_target.fas -strict > pos_286_miranda_results.txt
miranda pos_287_mirna.fas pos_287_target.fas -strict > pos_287_miranda_results.txt
miranda pos_288_mirna.fas pos_288_target.fas -strict > pos_288_miranda_results.txt
miranda pos_289_mirna.fas pos_289_target.fas -strict > pos_289_miranda_results.txt
